# Generated by Django 6.0.3 on 2026-04-08 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_anime_description_alter_genre_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='genre',
            name='description',
            field=models.TextField(),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('poster', models.ImageField(blank=True, null=True, upload_to='main_manga_poster/')),
                ('adaptation', models.ManyToManyField(blank=True, to='main.anime')),
                ('genres', models.ManyToManyField(to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='MangaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='manga_images/')),
                ('manga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='m_images', to='main.manga')),
            ],
        ),
    ]
