# Generated by Django 6.0.3 on 2026-04-08 17:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_anime_description_alter_genre_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.manga'),
        ),
        migrations.AlterField(
            model_name='manga',
            name='adaptation',
            field=models.ManyToManyField(blank=True, related_name='adaptations', to='main.anime'),
        ),
    ]
